<template>
<div id="app" class='container-fluid-sm m-0 background-white'>
    <navigation-bar @save="saveDataToLocalStorage" @toggleconsent="showConsentModal = true"/>
    <consent v-if='showConsentModal' @consentset="closeConsentModal"/>
    <streams />

    <analytics-dashboard :url="getLogURL"/>


</div>
</template>

<script>
import Streams from "./components/Streams.vue";
import AnalyticsDashboard from "./components/AnalyticsDashboard.vue"
import NavigationBar from "./components/NavigationBar.vue"
import Consent from './components/Consent.vue';
import { mapActions, mapGetters } from 'vuex';
import { v4 as uuidv4 } from 'uuid';

export default {
  name: 'App',
  components: {
    NavigationBar,
    Streams,
    AnalyticsDashboard,
    Consent
  },
  data() {
    return {
        showConsentModal: true,
    }
  },
  created(){
    this.$store.dispatch('setUsesLocalStorage', this.hasStorage());
    this.getUUID();
    this.checkConsent();
  },
  mounted(){
        this.loadFromLocalStorage();
        this.autoSave();

        let _this = this;
        window.addEventListener('pagehide', () => {_this.autoSave()});				//closing window
        window.addEventListener('beforeunload', () => {_this.autoSave()});			//refreshing page, changing URL
        window.addEventListener('pageshow', () => {_this.log({log:'analytics-interaction', type:'show'})});
  },
  computed:{
        ...mapGetters([
            'getLogURL',
            'getExperiment',
            'getCourse',
            'getLogConsent',
            'getSaved',
            'getTasks',
            'getIndicators',
            'getCentroids',
            'getUsesLocalStorage'
        ])
  },
  methods:{
        ...mapActions([
            'log'
        ]),
        hasStorage(){
            try {
                window.localStorage.setItem('test', 'storage');
                window.localStorage.removeItem('test');
                return true;
            } catch (exception) {
                return false;
            }
        },
        hasDataToLoad(exp){
            let item_name = exp + '-la-data';
            if(window.localStorage.getItem(item_name)){
                return true;
            } else{
                return false;
            }
        },
        loadFromLocalStorage(){
            let exp = this.getExperiment;
            if(this.getUsesLocalStorage && this.hasDataToLoad(exp)){

                this.loadData(exp);
                return true;

            } else{

                console.log('no local storage or data to load');
                return false;
            }
            
        },
        loadData(exp){
            if(window.localStorage.getItem(exp + '-la-data')){
                let data = window.localStorage.getItem(exp + '-la-data');
                data = JSON.parse(data);
                this.$store.dispatch('setSaved', data);
            }
        },
        saveDataToLocalStorage(){
            if(this.getUsesLocalStorage && this.getLogConsent){
                
                this.saveData();
                return true;
                
            } else{

                console.log('no localStorage allowed');
                return false;
            }
        },
        saveData(){
            let exp = this.getExperiment;
            let saved = this.getSaved;
            let taskcompletion = this.getTasks;
            let indicators = this.getIndicators;
            let student_centroid = this.getCentroids['student']
            let date = new Date();
            let to_save = {"date": date, "taskcompletion":taskcompletion, "indicators":indicators, 'student_centroid': student_centroid}
            saved.push(to_save);
            let data_json = JSON.stringify(saved);
            window.localStorage.setItem(exp + '-la-data', data_json);  
        },
        autoSave(){
            if(this.getSaved.length > 0){
                let latest_save = this.getSaved[this.getSaved.length - 1];
                let time_delta = new Date().getTime() - new Date(latest_save.date).getTime();
                //if it has been more than 12 hours since your last save then automatically save
                if(time_delta > 43200000){
                    this.saveDataToLocalStorage();
                }
            } else if(Object.keys(this.getTasks).length > 0){
                this.saveDataToLocalStorage();
            }
            

        },
        // Check for a UUID generated by the appropriate remote lab, if no UUID then generate one - have to check whether this should happen or if 
        //it should only look for one generated by the remote lab UI.
        getUUID(){
            let stored_uuid;
            let course = this.getCourse;
            let exp = this.getExperiment;
            const item = `uuid-${exp}-${course}`
            if(this.getUsesLocalStorage){
                stored_uuid = window.localStorage.getItem(item);
            } else {
                stored_uuid = null;
            }
            
            if(stored_uuid){
                this.$store.dispatch('setUUID', stored_uuid);
            } else{
                let uuid = uuidv4();
                this.$store.dispatch('setUUID', uuid);
                if(this.getUsesLocalStorage){
                    window.localStorage.setItem(item, uuid);
                }
                
            }
        },
        checkConsent(){
            let logging_consent;
            
            if(this.getUsesLocalStorage){
                let course = this.getCourse;
                let exp = this.getExperiment;
                const item = `consent-${exp}-${course}`
                logging_consent = window.localStorage.getItem(item);
            } else {
                logging_consent = null;
            }
            
            if(logging_consent == null){
                this.showConsentModal = true;
            
            } else{
                this.showConsentModal = false;
                this.$store.dispatch('setLoggingConsent', (logging_consent === 'true'));
            }
            
        },
        closeConsentModal(){
            this.showConsentModal = false;
        }
        
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
